name=MicroAsync
version=1.0.0
author=Łukasz Kaniak
maintainer=Łukasz Kaniak <lukaszkaniak@gmail.com>
sentence=Asynchronous programming primitives (Promises, Tasks) for microcontrollers.
paragraph=Library providing asynchrony to the microcontrollers in few popular trends known from higher level programing languages.
category=Other
url=https://github.com/nativeme/MicroAsync.git
architectures=*
